### ISSUE TITLE
fix Institutional email validation

### ISSUE THREAD

**Issue by caravinci** [overture-stack/enrolment#155]
the form doesn't show this field as mandatory, nor does it specify its value should be different from the "daco email" (which somehow seems to be required/assumed even though I'm not using DACO).
Also, why can it not be the same?

**Comment by b-f-chan** [comment]
"Daco e-mail" is a misnomer, there's a separate ticket to rename this in the database to just "e-mail", see issue #112.

They cannot be the same, as this was an explicit requirement from Michelle.  She didn't want people just copying and pasting their personal and/or billing e-mail as the institution.

Since we aren't validating the institution is "real" in any automatic way, nor are we currently supporting credit card charging/validation to validate who they are, often Michelle needs to contact or reach out to individuals directly to validate them.  She wanted at least to capture a "real" institutional website & contact that she could follow-up with if required, until we have real validation implemented.

The simplest (yes, maybe not effective, but this is what the workaround is) way was to for now enforce that the institution mail is different from the billing/personal contact mail.

**Comment by b-f-chan** [comment]
Reduced scope - Enforce that the two e-mails cannot be the same

**Comment by caravinci** [comment]
The enforcement for the two emails was already in place, so instead I've reworded the validation error message:
was "Institutional email must be different from daco email"
becomes "Institutional email must be different from your own email"

Furthermore, added "(Required)" to its placeholder e.g. "Institutional Email (Required)", and for consistency, did the same to any other required fields.

Deployed onto lab for testing.

**Comment by jmimico** [comment]
Was able to see both unique email enforcement errors so I believe this is working as expected.

**Comment by b-f-chan** [comment]
Also tested in lab:

- Unique e-mail error message appears correctly when trying to set institution e-mail = own registration e-mail
- "(Required)" label appears for all mandatory fields

Ready for PR review
