### ISSUE TITLE
[Security Vulnerability] Upgrade Multiple Packages

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/enrolment#157]
There are several security vulnerabilities to be addressed that have been opened in the past 1-2 months for Enrolment.

Specific Alerts below, please connect the individual PRs to this issue as required:

(1) https://github.com/overture-stack/enrolment/network/alert/enrolment-ui/yarn.lock/minimist/open

(2) https://github.com/overture-stack/enrolment/network/alert/enrolment-ui/yarn.lock/acorn/open

(3) https://github.com/overture-stack/enrolment/network/alert/enrolment-service/enrol/yarn.lock/minimist/open

(4) https://github.com/overture-stack/enrolment/network/alert/enrolment-service/enrol/yarn.lock/kind-of/open

(5) https://github.com/overture-stack/enrolment/network/alert/enrolment-ui/yarn.lock/kind-of/open

(6) https://github.com/overture-stack/enrolment/network/alert/enrolment-service/enrol/yarn.lock/set-value/open

(7) https://github.com/overture-stack/enrolment/network/alert/enrolment-service/enrol/yarn.lock/mixin-deep/open

**Comment by caravinci** [comment]
A few dependencies have been deprecated. This ticket will address those too.

![image.png](https://images.zenhubusercontent.com/5defce3f99bcf0b1b8a98d24/644ae78f-b586-4934-815e-dde5e2017850)

**Comment by caravinci** [comment]
As a result of the changes, a few important dependencies have forced upon the app noticeable changes, mainly in terms of styling.
Part of my implementation here addresses some of those, but for practicality and time pressure, I've only addressed the most noticeable differences leaving some subtleties still to be managed.

In other words, the appearance of the app will have changed a bit, but since it's functional in this current state, more adjustments can be done later if requested/necessary.

**Comment by b-f-chan** [comment]
Testing was done in #152, please see comments there, ready for PR review
