### ISSUE TITLE
Investigate if IT is Blocking E-mail Sending from Lab-Enrolment

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/enrolment#168]
Check if IT is blocking us from sending e-mail from lab-enrolment.

We're currently unable to test the new user invitation flow in this environment.  When a new user request is made for a project, no e-mail invite is sent out.  This works in prod.

Error logs captured from lab:

![image.png](https://images.zenhubusercontent.com/5c8bff46913aca2929d7074d/cc252cfb-7e3d-430b-abc7-cad0049d3929)

![image (1).png](https://images.zenhubusercontent.com/5c8bff46913aca2929d7074d/2a3e2fc4-233a-4c6e-9767-0086e43544da)

![image (2).png](https://images.zenhubusercontent.com/5c8bff46913aca2929d7074d/efd714c0-fd34-4bc5-8376-786a06ac0d26)

**Comment by caravinci** [comment]
Following up, while prepping to deploy to Prod:
The email server is bouncing all outgoing email from this server. Based on the server response, seems to me like they need to allowlist a few email addresses for us:
`...status=bounced (host <removed this host and ip from public view> said: 550 rejecting spoofed message (in reply to end of DATA command))`

Will proceed to check on the status of this from the prod server, just to ensure nothing breaks upon deployment.
(i.e. be able to distinguish whether anything is caused by code changes, or environment)
